import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideFirebaseApp, initializeApp } from '@angular/fire/app';
import { provideFirestore, getFirestore } from '@angular/fire/firestore';
import { provideAuth, getAuth } from '@angular/fire/auth';
import {
  LUCIDE_ICONS,
  LucideIconProvider,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowUpNarrowWide,
  Briefcase,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Coffee,
  Download,
  Droplet,
  Eye,
  FileText,
  Home,
  Info,
  Layers,
  List,
  Lock,
  LogOut,
  Menu,
  Plus,
  Search,
  SquarePen,
  Star,
  Trash2,
  User,
  Users,
  Wind,
  X,
} from 'lucide-angular';

import { routes } from './app.routes';
import { firebaseConfig } from './config/firebase.config';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideFirebaseApp(() => initializeApp(firebaseConfig)),
    provideFirestore(() => getFirestore()),
    provideAuth(() => getAuth()),
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider({
        ArrowDownWideNarrow,
        ArrowLeft,
        ArrowUpNarrowWide,
        Briefcase,
        Calendar,
        Check,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        Coffee,
        Download,
        Droplet,
        Eye,
        FileText,
        Home,
        Info,
        Layers,
        List,
        Lock,
        LogOut,
        Menu,
        Plus,
        Search,
        SquarePen,
        Star,
        Trash2,
        User,
        Users,
        Wind,
        X,
      }),
    },
  ],
};
